### ISSUE TITLE
fake ws2801

### ISSUE THREAD

**Issue by frustrader** [tvdzwan/hypercon#14]
I have a lot trouble to get a bright white color (stays purple)
Now i bought another ws2801 led strip "brand epistar" and have a bright white color. 
Wich brand ws2801 led strip is recommend? Or should i just go for apa102?

**Comment by brindosch** [comment]
I didn´t know there are ws2801 fakes out there, was there a big price difference?
I recommend anyway APA102 because of the following reasons:
-The RGB Byte Order stays the same, (ws2801 changes from strip to strip) so you have problems, if you mix 2 stripes (for example on a second tv).
- Robust design, just have a look on a picture of both. That big ICs with many soldering points on a flexible stripe leads to broken contacts and a faulty sripe
-leds/m count: APA102 goes up to 144leds/m you never want to use this. But people reported if they use a TV that have a distance of around 5cm to the wall they have better results with 60leds/m.
I use 36leds/m for a distance of around 20-25cm to the wall
-Colors: i don´t know if this is really related to apa102, but i just use a gamma of 1,75 1,75 1,75 and a whitelevel of 0,4 0,4 0,2 (which lowers the brightness and matching TV white (evening)) that´t it. If i see some really strange values out there

**Comment by frustrader** [comment]
Thanks for the fast reply☺
No there was no big price difference!
Okay i will go for the apa102! Is there a brand you recommend? Is epistar
genuine?

I didn´t know there are ws2801 fakes out there, was there a big price
difference?
I recommend anyway APA102 because of the following reasons:
-The RGB Byte Order stays the same, (ws2801 changes from strip to strip) so
you have problems, if you mix 2 stripes (for example on a second tv).

   - Robust design, just have a look on a picture of both. That big ICs
   with many soldering points on a flexible stripe leads to broken contacts
   and a faulty sripe -leds/m count: APA102 goes up to 144leds/m you never
   want to use this. But people reported if they use a TV that have a distance
   of around 5cm to the wall they have better results with 60leds/m. I use
   36leds/m for a distance of around 20-25cm to the wall -Colors: i don´t know
   if this is really related to apa102, but i just use a gamma of 1,75 1,75
   1,75 and a whitelevel of 0,4 0,4 0,2 (which lowers the brightness and
   matching TV white (evening)) that´t it. If i see some really strange values
   out there

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/tvdzwan/hypercon/issues/14#issuecomment-203887466>

**Comment by brindosch** [comment]
Yes, epistar is ok

**Comment by frustrader** [comment]
I found a seller on aliexpress who sells apa102 for a good price, but you
have to choose for white or yellow color?
I'm confused, what do they mean with that?
Isn't this the right one?
Op 31 mrt. 2016 15:30 schreef "brindosch" <notifications@github.com>:

**Comment by brindosch** [comment]
There is a apa102 "crises" ongoing.
why? no idea
If you could choose in between that colors they could be wrong

**Comment by tpmodding** [comment]
white or yellow color means in the most cases the stripe color, and yellow is the black stripe...

should declared in the description

**Comment by frustrader** [comment]
Sorry for the late reply. 

Ah that's explains alot. 
I'm trying to get apa102 but there's indeed a crisis going on!  I found a seller on aliexpress but he has 2 different types: the mainland chip and the taiwan chip which is twice as expensive then the mainland. Is there a big difference in quality  between them?

**Comment by brunano21** [comment]
@frustrader 
Hey, just wondering if you have found any temporary solution for the fakes ws2801 - Basically I have the same issue :/ damn it!

**Comment by brindosch** [comment]
I will close this :)

**Comment by brunano21** [comment]
@frustrader Hey, did you buy the apa102 at the end? any comment/feedback?

**Comment by frustrader** [comment]
@brunano21 yes they came with the mail last weekend, installed it last night and looks very good!
didnt had to change the color values.  but i still have some problems with grey scenes they show up red or blue, but much better then the ws2801
I
