### ISSUE TITLE
Different amount of LEDs on top and bottom without a gap on bottom

### ISSUE THREAD

**Issue by DerFlob** [tvdzwan/hypercon#6]
Would it be possible to add a feature to generate a configuration with different amounts of LEDs on the top on bottom? I know that there is the bottom gap option, but that is not what I need. 

The "missing" LEDs for my system are not in the middle of the row, but on the sides. The bottom is a non-stop, centred strip, that just doesn't have as many LEDs as the top one.

Thank you
DerFlob

**Comment by brindosch** [comment]
Added your wish to the wishlist

Closed

**Comment by MathijsG** [comment]
Will this ever see light (pun intended) in Hypercon? I have same strips for my tv, but the bottom is, like many tv's, bulky and rounded, so while I barely have enough space for my 24 leds at the bottom, I have this problem that at the top horizontal strip I have 2 leds too many to fit, because of the flat size of the TV on that side.

I would need something like differentiation between top and bottom. If I would just setup the horizontal bars as having 22 leds (because that's what my top part has effectively, I currently just folded the two side leds back) the bottom goed weird because their it is effectively 24 leds.

Here you can see it: 
![image](https://cloud.githubusercontent.com/assets/529552/18675585/1f462cae-7f53-11e6-9eff-946711c0d20e.png)

I have re-aligned them later, but the problem still is how to deal with this size difference.

**Comment by milankomoravcik** [comment]
Hello guys, i would like to ask if there is solution for this :)
if i have stand for tv in middle as on picture its not problem, i make a gap of 5 leds in middle, but i havent this kind of stand and also thinking about putting it on wall later
thanks

**Comment by milankomoravcik** [comment]
i solved it by manual edit of config
firstly -> create config_1 with less amount of leds (horizontal - example 85)
then -> create config_2 with more amount of leds (horizontal - example 88)
take from config_2 the bottom horizontal in my way led 50 to 137
paste it in config_1 over leds in my way 50 to 134 ...
all led above change number +3 :)
done

after doing that i think about that i dont need to change numbers if i setup offset where the bottom leds are on the end ...but i had already taped and soldered led on tv so i cant do it ...simple in my way i have 273 led so i should setup offset to 273 :) and then i just should switch only end of json config_1 with end starting with led 191 from config_2

**Comment by potalifs** [comment]
Same situation, why don't put the horizontal configuration like vertical, indipendent sides?? I don't understand. Sorry for my English

**Comment by milankomoravcik** [comment]
but how i tell hypercon that left is bottom ?i think it doesnt support changing vertical with horizontal ...

**Comment by potalifs** [comment]
Sorry, I write bad, I meant why is not added this feature in hypercon? Sorry for my English.

**Comment by MathijsG** [comment]
I guess we are a minority having these issues :-P. Maybe raise a new issue instead of replying in this closed one?
